### ISSUE TITLE
Issue with HiPerMod benchmarks in IDA

### ISSUE THREAD

**Issue by casella** [marco-compiler/marco#15]
As I understand from @mscuttari, the ThermalChipOO and Methanol benchmarks don't work well with IDA because of a known issue with the generation of derivatives of the sum() reduction operator, which is required to pass the Jacobians to IDA. This feature is currently (kind of?) implemented in a development branch, which is not yet merged to master.

**Comment by mscuttari** [comment]
f4e03fc should have fixed the issue.
More testing may be necessary to confirm it, but for now I'm closing the issue.
